 # print("\nThông tin DataFrame:")
    # print(data.info())
    # print("\nSố lượng giá trị thiếu trong mỗi cột:")
    # print(data.isna().sum())
    # print("\nSố lượng bản ghi bị trùng lặp:")
    # print(data.duplicated().sum())